services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - "./:/var/www/html"
      - "../moodledata:/var/www/moodledata"
      - "../phpu_moodledata:/var/www/phpu_moodledata"
      - "./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
    ports:
      - "80:80"
    environment:
      MOODLE_DOCKER_RUNNING: 1
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBUSER: moodle
      MOODLE_DOCKER_DBPASS: "m@0dl3ing"
      MOODLE_DOCKER_DBTYPE: mysqli
      MOODLE_DOCKER_DBCOLLATION: utf8mb4_bin
  db:
    image: mysql:8.0
    command: >
                --character-set-server=utf8mb4
                --collation-server=utf8mb4_bin
                --skip-log-bin
    ports:
      - "3306:3306/tcp"
    volumes:
      - vol_academy_mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "m@0dl3ing"
      MYSQL_USER: moodle
      MYSQL_PASSWORD: "m@0dl3ing"
      MYSQL_DATABASE: moodle

volumes:
  vol_academy_mysql_data:
