#!/usr/bin/env bash

# Start Apache
echo "Apache is running"
apachectl -D FOREGROUND

# Start Moodle Docker PHP Entrypoint
echo "Moodle Docker PHP Entrypoint"
moodle-docker-php-entrypoint

# Start CRON
echo "RUN CRON Jobs"
env >> /etc/environment
service cron restart
crontab /etc/cron.d/my-cron
