# =============================================================================
# DEVELOPMENT - Local development with hot-reload
# =============================================================================
# Usage:
#     docker compose -f .devcontainer/compose/base.yml -f .devcontainer/compose/db.yml -f .devcontainer/compose/dev.yml up -d
# =============================================================================

services:
  moodle:
    image: leodg/moodle-academy:development
    restart: unless-stopped
    env_file:
      - ../env/dev.env
    environment:
      - MOODLE_URL=https://dev.ivana.academy
      - ENVIRONMENT=development
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=0
      - MOODLE_DEBUG=DEVELOPER
      - MOODLE_DEBUG_DISPLAY=1
      - MOODLE_DATA=${MOODLE_DOCKER_DATA:-/var/www/moodledata}
      - APACHE_LOG_DIR=/var/log/apache2
    depends_on:
      db:
        condition: service_healthy
    secrets:
    - ssl_cert
    - ssl_key
    networks:
      - moodle_network
    ports:
      - "${MOODLE_HTTP_PORT:-80}:80"
      - "${MOODLE_HTTPS_PORT:-443}:443"
      - "9003:9003" # Xdebug
    volumes:
      - "${MOODLE_HOST_WWWROOT:-../../}:${MOODLE_DOCKER_WWWROOT:-/var/www/html}"
      - "${MOODLE_HOST_DATA:-../../../moodledata}:${MOODLE_DOCKER_DATA:-/var/www/moodledata}"
      - /var/www/html/.devcontainer  # no show folder
      - composer_cache:/root/.composer
      - ../php/opcache-sandbox.ini:/usr/local/etc/php/conf.d/opcache.ini:ro
      - ../php/php-dev-custom.ini:/usr/local/etc/php/conf.d/zzz-custom.ini:ro
      - ../apache/moodle-dev-performance.conf:/etc/apache2/conf-enabled/moodle-performance.conf:ro

    deploy:
      resources:
        limits:
          memory: 450M
        reservations:
          memory: 256M

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 30s


