; Configuração recomendada para Moodle
opcache.enable=1
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=10000
opcache.use_cwd=1
opcache.save_comments=1
opcache.enable_file_override=0

; re-validate of timestamps, is set to false (0) by default, is overridden in local docker-compose
opcache.validate_timestamps=${PHP_OPCACHE_VALIDATE_TIMESTAMPS}

; don't check edit file
opcache.revalidate_freq=0