name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: leodg/moodle-academy:latest
          build-args: |
            MOODLE_DBHOST{{ secrets.MOODLE_DBHOST }}
            MOODLE_DBNAME{{ secrets.MOODLE_DBNAME }}
            MOODLE_DBUSER={{ secrets.MOODLE_DBUSER }}
            MOODLE_DBPASS={{ secrets.MOODLE_DBPASS }}
            MOODLE_URL={{ vars.MOODLE_URL }}


  deploy:
    needs: docker
    runs-on: self-hosted

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Deploy via SSH by RSYNC
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          SCRIPT_BEFORE: |
            sudo apt install rsync -y
          SCRIPT_AFTER: |
            whoami
            ls -al
            echo $RSYNC_STDOUT

      - name: Deploy to EC2 Instance
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop moodle || true
            docker rm moodle || true
            docker pull leodg/moodle-academy:latest
            docker run --name moodle -p 80:80 -v $PWD:/var/www/html

